workflows:
  warehouse-tracker-android:
    name: Warehouse Container Tracker Android
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        # Environment variables will be set in CodeMagic UI
        GOOGLE_SHEETS_SPREADSHEET_ID: Encrypted(...)
        GOOGLE_SERVICE_ACCOUNT_EMAIL: Encrypted(...)
        GOOGLE_SERVICE_ACCOUNT_JSON: Encrypted(...)
        ADMIN_EMAIL: Encrypted(...)
        FIREBASE_PROJECT_ID: Encrypted(...)
        FIREBASE_STORAGE_BUCKET: Encrypted(...)
        FIREBASE_MESSAGING_SENDER_ID: Encrypted(...)
        FIREBASE_API_KEY: Encrypted(...)
      groups:
        - google_play
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > android/local.properties
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter unit tests
        script: |
          flutter test
      - name: Build APK
        script: |
          flutter build apk --release
      - name: Build App Bundle
        script: |
          flutter build appbundle --release
    artifacts:
      - build/app/outputs/**/*.apk
      - build/app/outputs/**/*.aab
    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true

  warehouse-tracker-ios:
    name: Warehouse Container Tracker iOS
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        # Environment variables will be set in CodeMagic UI
        GOOGLE_SHEETS_SPREADSHEET_ID: Encrypted(...)
        GOOGLE_SERVICE_ACCOUNT_EMAIL: Encrypted(...)
        GOOGLE_SERVICE_ACCOUNT_JSON: Encrypted(...)
        ADMIN_EMAIL: Encrypted(...)
        FIREBASE_PROJECT_ID: Encrypted(...)
        FIREBASE_STORAGE_BUCKET: Encrypted(...)
        FIREBASE_MESSAGING_SENDER_ID: Encrypted(...)
        FIREBASE_API_KEY: Encrypted(...)
      groups:
        - app_store
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter unit tests
        script: |
          flutter test
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      app_store:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
