name: warehouse_container_tracker
description: A Flutter app for tracking warehouse container unloading/loading

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1

  # Utilities
  intl: ^0.19.0
  fluttertoast: ^8.2.4
  shared_preferences: ^2.2.2

  # UI
  cupertino_icons: ^1.0.6
  reorderables: ^0.6.0

  # Camera & Image Processing
  camera: ^0.10.5+5
  image: ^4.1.3
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  path: ^1.8.3

  # PDF Generation
  pdf: ^3.10.7
  printing: ^5.11.1

  # Google Sheets & Firebase
  googleapis: ^11.4.0
  googleapis_auth: ^1.4.1
  http: ^1.1.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.5.6
  firebase_messaging: ^14.7.9

  # Permissions
  permission_handler: ^11.0.1

  # Connectivity
  connectivity_plus: ^5.0.2

  # Email
  flutter_email_sender: ^6.0.2

  # Environment
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:
  uses-material-design: true
  
  assets:
    - assets/images/